/*
 * Сервис баннеров
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type InlineResponse201 struct {
	// Идентификатор созданного баннера
	BannerId int32 `json:"banner_id,omitempty"`
}
